package com.example.kakoang4create.model;

public enum Category {
    PORNOGRAFIA,ALKOHOL,NARKOTYKI,CYBERSEKS,HAZARD,SPORT,ZAKUPOHOLIZM,PRACOHOLIZM,PAPIEROSY,WIARA,
    OBŻARSTWO,SEKSOHOLIZM,TECHNOLOGY,ZABURZENIA_ODZYWIANIA, LEKOMANIA
}
